<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>org</string>
		<string>tasks</string>
	</array>
	<key>name</key>
	<string>orgmode</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(?x)
^(\*+)               # leading stars
\s*([A-Z_]{2,})?     # todo keywords
\s*(\[\#[A-Ca-c]\])? # priority
\s*(?=\s+[A-Za-z]+)  # expected heading text
</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.heading.orgmode</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.todo.orgmode</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.other.priority.orgmode</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Outline headings</string>
			<key>contentName</key>
			<string>entity.name.section.orgmode</string>
			<key>end</key>
			<string>(?=\s*$\n?)</string>
			<key>name</key>
			<string>markup.heading.orgmode</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#heading-inline</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>^-{5,}$</string>
			<key>name</key>
			<string>meta.separator.orgmode</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*([-+]|\s+\*)\s+(.*?)\s+::</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.list.orgmode</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.bold.definition.orgmode</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>meta.list.definition.orgmode</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*?([-+]|\s+\*|\d+[).])</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.list.orgmode</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>meta.list.plain.orgmode</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#list-inline</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^#\+(BEGIN_(QUOTE|VERSE|CENTER))$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.block.orgmode</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^#\+(END_\2)$</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.block.orgmode</string>
				</dict>
			</dict>
			<key>name</key>
			<string>markup.quote.orgmode</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^#[^+].*$</string>
			<key>name</key>
			<string>comment.line.number-sign.orgmode</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^:(PROPERTIES):$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.drawer.orgmode</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^:(END):$</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.drawer.orgmode</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.drawer.properties.orgmode</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#properties</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^:(.+):$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.drawer.orgmode</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^:(END):$</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.drawer.orgmode</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.drawer.other.orgmode</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>#\+(BEGIN_LaTeX)$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.block.orgmode</string>
				</dict>
			</dict>
			<key>end</key>
			<string>#\+(END_LaTeX)$</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.block.orgmode</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.block.latex.orgmode</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.tex.latex</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>#\+(BEGIN_HTML)$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.block.orgmode</string>
				</dict>
			</dict>
			<key>end</key>
			<string>#\+(END_HTML)$</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.block.orgmode</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.block.html.orgmode</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>#\+(BEGIN_SRC)\s+(python)\s*(.*)$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.block.orgmode</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.other.language.orgmode</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.other.header-args.orgmode</string>
				</dict>
			</dict>
			<key>end</key>
			<string>#\+(END_SRC)$</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.block.orgmode</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.block.source.python.orgmode</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.python</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>#\+(BEGIN_SRC)\s+(ruby)\s*(.*)$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.block.orgmode</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.other.language.orgmode</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.other.header-args.orgmode</string>
				</dict>
			</dict>
			<key>end</key>
			<string>#\+(END_SRC)$</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.block.orgmode</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.block.source.ruby.orgmode</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.ruby</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>#\+(BEGIN_SRC)\s+((?:emacs-)?lisp)\s*(.*)$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.block.orgmode</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.other.language.orgmode</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.other.header-args.orgmode</string>
				</dict>
			</dict>
			<key>end</key>
			<string>#\+(END_SRC)$</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.block.orgmode</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.block.source.lisp.orgmode</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.lisp</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>#\+(BEGIN_(SRC|EXAMPLE))(?:\s+([\w-]+)?\s*(.*))?$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.block.orgmode</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.other.language.orgmode</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.other.header-args.orgmode</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>markup.raw.block.orgmode</string>
			<key>end</key>
			<string>#\+(END_\2)$</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.block.orgmode</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.block.source.other.orgmode</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>#\+(OPTIONS):</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.pragma.orgmode</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>meta.pragma.options.orgmode</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.option.orgmode</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.other.option.orgmode</string>
						</dict>
					</dict>
					<key>match</key>
					<string>([^\s]+):([^\s]+)</string>
					<key>name</key>
					<string>meta.option.orgmode</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>#\+(CALL):\s+[A-Za-z-]+(?:\[([^\]]*)\])?\(?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.pragma.orgmode</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.other.header-args.orgmode</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)?([^)]*)$</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.other.header-args.orgmode</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.pragma.call.orgmode</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.header-args.orgmode</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\w+)=</string>
					<key>name</key>
					<string>meta.assignment.orgmode</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.pragma.orgmode</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.pragma.orgmode</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^#\+([a-zA-Z_-]+): ?(.*)$</string>
			<key>name</key>
			<string>meta.pragma.orgmode</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#inline</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>heading-inline</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.quoted.keyword.orgmode</string>
						</dict>
					</dict>
					<key>match</key>
					<string>:([^:]*)(?=:)</string>
					<key>name</key>
					<string>meta.keyword.orgmode</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
			</array>
		</dict>
		<key>inline</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&lt;=^|[.,:;\s])/[^/]+/(?=$|[.,:;\s])</string>
					<key>name</key>
					<string>markup.italic.orgmode</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=^|[.,:;\s])\*[^*]+\*(?=$|[.,:;\s])</string>
					<key>name</key>
					<string>markup.bold.orgmode</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=^|[.,:;\s])_[^_]+_(?=$|[.,:;\s])</string>
					<key>name</key>
					<string>markup.underline.orgmode</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=^|[.,:;\s])([~=]).+?\1(?=$|[.,:;\s])</string>
					<key>name</key>
					<string>markup.raw.inline.orgmode</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>markup.underline.link.orgmode</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.other.link.orgmode</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\[(?:\[([^\]]*)\])?\[([^\]]*)\]\]</string>
					<key>name</key>
					<string>meta.link.orgmode</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?:http|ftp)s?:\/\/\S+</string>
					<key>name</key>
					<string>markup.underline.url.orgmode</string>
				</dict>
			</array>
		</dict>
		<key>list-inline</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\[[ -X]\]</string>
					<key>name</key>
					<string>keyword.operator.checkbox.orgmode</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
			</array>
		</dict>
		<key>properties</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.property.orgmode</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.unquoted.propval.orgmode</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^:([A-Za-z_]+):\s(.*)$</string>
					<key>name</key>
					<string>meta.property.orgmode</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.orgmode</string>
	<key>uuid</key>
	<string>e4fb86ca-d96b-4094-ac47-d14dbae2d088</string>
</dict>
</plist>
