<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>org</string>
	</array>
	<key>name</key>
	<string>Org</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#block</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>block</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#heading</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#quote</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#directive</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#lists</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#table</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#paragraph</string>
				</dict>
			</array>
			<key>repository</key>
			<dict>
				<key>comment</key>
				<dict>
					<key>match</key>
					<string>(?:^|\G)#(?=[^+]).*$\n?</string>
					<key>name</key>
					<string>comment.line.org</string>
				</dict>
				<key>directive</key>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.config.org</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.config.value.org</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?:^|\G)#\+([A-Z_]+):\s*(.*)\s*$\n?</string>
					<key>name</key>
					<string>comment.line.directive.org</string>
				</dict>
				<key>heading</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(?:^|\G)(\*{1,6})\s+(?=[\S[^#]])</string>
							<key>contentName</key>
							<string>entity.name.section.org</string>
							<key>end</key>
							<string>\s*$\n?</string>
							<key>name</key>
							<string>markup.heading.${1/(\*)(\*)?(\*)?(\*)?(\*)?(\*)?/${6:?6:${5:?5:${4:?4:${3:?3:${2:?2:1}}}}}/}.org</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#inline</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#tag</string>
								</dict>
							</array>
							<key>repository</key>
							<dict>
								<key>tag</key>
								<dict>
									<key>patterns</key>
									<array>
										<dict>
											<key>begin</key>
											<string>:</string>
											<key>end</key>
											<string>:</string>
											<key>name</key>
											<string>keyword.tag.org</string>
										</dict>
									</array>
								</dict>
							</dict>
						</dict>
					</array>
				</dict>
				<key>lists</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(^|\G)([ ]{0,3})([+-])([ ]{1,3}|\t)</string>
							<key>beginCaptures</key>
							<dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.list.org</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>Currently does not support un-indented second lines.</string>
							<key>name</key>
							<string>markup.list.unnumbered.org</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#list_paragraph</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#block</string>
								</dict>
							</array>
							<key>while</key>
							<string>\G([ ]{4}|\t|$)</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>(^|\G)([ ]{0,3})([0-9]+[).])([ ]{1,3}|\t)</string>
							<key>beginCaptures</key>
							<dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.list.org</string>
								</dict>
							</dict>
							<key>name</key>
							<string>markup.list.numbered.org</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#block</string>
								</dict>
							</array>
							<key>while</key>
							<string>\G([ ]{4}|\t|$)</string>
						</dict>
					</array>
				</dict>
				<key>paragraph</key>
				<dict>
					<key>begin</key>
					<string>(^|\G)(?=\S)</string>
					<key>name</key>
					<string>meta.paragraph.org</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
					</array>
					<key>while</key>
					<string>(^|\G)(?!\s*$|\*)</string>
				</dict>
				<key>quote</key>
				<dict>
					<key>begin</key>
					<string>(?:^|\G)(#\+BEGIN_QUOTE)\s*$\n?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.quote.org</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?:^|\G)(#\+END_QUOTE)\s*$\n?</string>
					<key>name</key>
					<string>markup.quote.org</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
					</array>
				</dict>
				<key>table</key>
				<dict>
					<key>begin</key>
					<string>(?:^|\G)\|</string>
					<key>name</key>
					<string>markup.other.table.org</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#hline</string>
						</dict>
					</array>
					<key>repository</key>
					<dict>
						<key>hline</key>
						<dict>
							<key>match</key>
							<string>(?:^|\G)\|[ |-+]+\|$\n?</string>
							<key>name</key>
							<string>markup.other.table.hline.org</string>
						</dict>
					</dict>
					<key>while</key>
					<string>\G\|</string>
				</dict>
			</dict>
		</dict>
		<key>inline</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?&lt;!\S)/</string>
					<key>end</key>
					<string>/(?!\S)</string>
					<key>name</key>
					<string>markup.italic.org</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\*</string>
					<key>end</key>
					<string>\*</string>
					<key>name</key>
					<string>markup.bold.org</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>_</string>
					<key>end</key>
					<string>_</string>
					<key>name</key>
					<string>markup.underline.org</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(=|~)</string>
					<key>end</key>
					<string>\1</string>
					<key>name</key>
					<string>markup.raw.inline.org</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\+</string>
					<key>end</key>
					<string>\+</string>
					<key>name</key>
					<string>markup.deleted.org</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.org</string>
	<key>uuid</key>
	<string>DADB21F2-7121-473F-B029-7487CEFDF32F</string>
</dict>
</plist>
